[package]
name = "bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
#cxx = "1.0.183"

[build-dependencies]
bindgen = "0.72.1"
pkg-config = "0.3.32"
#vcpkg = "0.2.15"
#cmake = "0.1.54"
#cxx-build = "1.0.183"
